name: Python application packaging      

on:
  push:
    branches:
      - "main"

jobs:
  build-and-upload:
    runs-on: windows-2022
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.x"
          cache: "pip"
          
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependences
        run: |
          python -m pip install --upgrade pip pyinstaller
          python -m pip install -r requirements.txt
      
      - name: Pack to Executable
        run: pyinstaller --log-level ERROR --noconfirm --clean --name "Chat Maze" --add-data ./src/*.json:. ./src/Main.py  
      
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: "Chat Maze"
          path: ./dist
